# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\x05greet\",\n\rClientMessage\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\rServerMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\rReportMessage\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04json\x18\x02 \x01(\t\"V\n\x10IndicatorMessage\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x11\n\tindicator\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65tector\x18\x04 \x01(\t\"9\n\x10ReportXIndicator\x12\x10\n\x08idReport\x18\x01 \x01(\t\x12\x13\n\x0bidIndicator\x18\x02 \x01(\t\";\n\x0f\x43omprobationMD5\x12\n\n\x02IP\x18\x01 \x01(\t\x12\x0b\n\x03md5\x18\x02 \x01(\t\x12\x0f\n\x07\x61rchive\x18\x03 \x01(\t\"9\n\x0fSpecificRequest\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t2\x84\x05\n\rCommunication\x12:\n\x0cSubmitReport\x12\x14.greet.ReportMessage\x1a\x14.greet.ServerMessage\x12L\n\x1a\x42idirectionalCommunication\x12\x14.greet.ClientMessage\x1a\x14.greet.ServerMessage(\x01\x30\x01\x12@\n\x0fIndicatorReport\x12\x17.greet.IndicatorMessage\x1a\x14.greet.ServerMessage\x12\x44\n\x13SaveIndicatorReport\x12\x17.greet.ReportXIndicator\x1a\x14.greet.ServerMessage\x12\x45\n\x15ServerComprobationMD5\x12\x16.greet.ComprobationMD5\x1a\x14.greet.ServerMessage\x12K\n\x18StreamingServerIndicator\x12\x14.greet.ClientMessage\x1a\x17.greet.IndicatorMessage0\x01\x12\x45\n\x15StreamingServerReport\x12\x14.greet.ClientMessage\x1a\x14.greet.ReportMessage0\x01\x12\x45\n\x10IndicatorRequest\x12\x16.greet.SpecificRequest\x1a\x17.greet.IndicatorMessage0\x01\x12?\n\rReportRequest\x12\x16.greet.SpecificRequest\x1a\x14.greet.ReportMessage0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTMESSAGE._serialized_start=30
  _CLIENTMESSAGE._serialized_end=74
  _SERVERMESSAGE._serialized_start=76
  _SERVERMESSAGE._serialized_end=108
  _REPORTMESSAGE._serialized_start=110
  _REPORTMESSAGE._serialized_end=151
  _INDICATORMESSAGE._serialized_start=153
  _INDICATORMESSAGE._serialized_end=239
  _REPORTXINDICATOR._serialized_start=241
  _REPORTXINDICATOR._serialized_end=298
  _COMPROBATIONMD5._serialized_start=300
  _COMPROBATIONMD5._serialized_end=359
  _SPECIFICREQUEST._serialized_start=361
  _SPECIFICREQUEST._serialized_end=418
  _COMMUNICATION._serialized_start=421
  _COMMUNICATION._serialized_end=1065
# @@protoc_insertion_point(module_scope)
